### ISSUE TITLE
能够将录屏实时投影到电视上吗？

### ISSUE THREAD

**Issue by dota2AndTI** [PanoVideo/video-call-samples#10]
能够将录屏实时投影到电视上吗？

**Comment by vanezhang** [comment]
你好 不能直接投影。可以通过发送视频的方式来实现传输。

**Comment by vanezhang** [comment]
如果您对此感兴趣，可以访问我们的官网：https://www.pano.video/index.html
页面底部左侧有一个"售前咨询"。

**Comment by dota2AndTI** [comment]
我需要实时的视频传输，投影到电视上
